export enum IMAGES {
  //dark icons
  home = require('../assets/images/home.png'),
  upload = require('../assets/images/upload.png'),
  account = require('../assets/images/account.png'),
  email = require('../assets/images/email.png'),
  lock = require('../assets/images/lock.png'),
  eye = require('../assets/images/eye.png'),
  hidden = require('../assets/images/hidden.png'),
  call = require('../assets/images/call.png'),
  social = require('../assets/images/social.png'),
  male = require('../assets/images/male.png'),
  female = require('../assets/images/female.png'),
  menu = require('../assets/images/menu.png'),
  plus = require('../assets/images/plus.png'),
  close = require('../assets/images/close.png'),
  camera = require('../assets/images/camera.png'),
  gallery = require('../assets/images/gallery.png'),
  dots = require('../assets/images/dots.png'),

  //light icons
  home_light = require('../assets/images/home_light.png'),
  upload_light = require('../assets/images/upload_light.png'),
  account_light = require('../assets/images/account_light.png'),
  email_light = require('../assets/images/email_light.png'),
  lock_light = require('../assets/images/lock_light.png'),
  eye_light = require('../assets/images/eye_light.png'),
  hidden_light = require('../assets/images/hidden_light.png'),
  call_light = require('../assets/images/call_light.png'),
  male_light = require('../assets/images/male_light.png'),
  female_light = require('../assets/images/female_light.png'),
  menu_light = require('../assets/images/menu_light.png'),
  plus_light = require('../assets/images/plus_light.png'),
  close_light = require('../assets/images/close_light.png'),
  camera_light = require('../assets/images/camera_light.png'),
  gallery_light = require('../assets/images/gallery_light.png'),
  dots_light = require('../assets/images/dots_light.png'),
}
